#!/usr/bin/env bash
# displays  simple clock
h=0
while((h <= 24))
do
    echo "Hour: $h"
    m=1
        while((m < 60))
        do
            echo "$m"
            ((m+=1))
        done
    ((h+=1))
done
