#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
apt-get update
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen      80;
    listen      [::]:80;
    root        /etc/nginx/html;
    index       index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/your_domain
service nginx restart
