#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm index.nginx-debian.html;;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
