#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://github.com/hazemghaly;
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart                       
