#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/error404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/error404.html
printf %s "server {
    listen      80;
    listen      [::]:80;
    root        /etc/nginx/html;
    index       index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /error404.html;
    location = /error_404.html {
        root /etc/nginx/html;
        internal;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
