#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart                       
