#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee  /etc/nginx/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee  /etc/nginx/html/404.html
sudo echo "server {
    listen      80;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
    rewrite ^\/redirect_me https://github.com/hazemghaly permanent;
    root        /etc/nginx/html;
    index       index.html;
    location /redirect_me {
        return 301 https://github.com/hazemghaly;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
        internal;
    }
}
" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
