#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine 
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | /etc/nginx/html/index.html
echo "Ceci n'est pas une page" | /etc/nginx/html/error404.html
echo "server {
    listen      80;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
    rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    root        /etc/nginx/html;
    index       index.html;
    location /redirect_me {
        return 301 https://github.com/hazemghaly;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
        internal;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
