#!/usr/bin/env bash
#config a new Ubuntu machine nginx
sudo service nginx stop
sudo apt purge -y haproxy
sudo apt-get -y upgrade
sudo apt-get -y install haproxy=2.8.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "frontend hazem_frontend
        bind *:80
        mode http
        default_backend hazem_backend
backend hazem_backend
        balance roundrobin
        server 345269-web-01 100.27.12.93:80 check
        server 345269-web-02 54.146.89.146:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy start
