#!/usr/bin/env bash
# display fils contant
if  [[ -d "school" ]] || [ -f "school" ]; then
    echo "school file exists"
    if [ ! -s "school" ]; then
        echo "school is empty"
    else
        echo "school is not empty"
    fi
    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
